language: php

sudo: false

matrix:
  include:
    - php: 5.5
      env: PROCESS_CODECLIMATE=true
    - php: 5.6
    - php: 7.0
    - php: hhvm


before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist
  - echo 'zend_extension=xdebug.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: ./test/bin/ci.bash summary
